// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTrafficLight_Infrastructure.Data;

#nullable disable

namespace SmartTrafficLight_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422183028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.Intersection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumberOfLanes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Intersections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Location = "Ho Chi Minh City",
                            Name = "Nga Tu Hang Xanh",
                            NumberOfLanes = 4
                        });
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.TrafficData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntersectionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TrafficDatas");
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.TrafficLight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IntersectionId");

                    b.ToTable("TrafficLights");
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.ValueObjects.PredictionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PredictAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IntersectionId");

                    b.ToTable("PredictionResults");
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.TrafficData", b =>
                {
                    b.HasOne("SmartTrafficLight_Domain.Entities.Intersection", "Intersection")
                        .WithMany("TrafficDatas")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.TrafficLight", b =>
                {
                    b.HasOne("SmartTrafficLight_Domain.Entities.Intersection", "Intersection")
                        .WithMany("TrafficLights")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartTrafficLight_Domain.ValueObjects.TimingConfig", "CurrentTiming", b1 =>
                        {
                            b1.Property<Guid>("TrafficLightId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("GreenDuration")
                                .HasColumnType("int")
                                .HasColumnName("GreenDuration");

                            b1.Property<int>("RedDuration")
                                .HasColumnType("int")
                                .HasColumnName("RedDuration");

                            b1.Property<int>("YellowDuration")
                                .HasColumnType("int")
                                .HasColumnName("YellowDuration");

                            b1.HasKey("TrafficLightId");

                            b1.ToTable("TrafficLights");

                            b1.WithOwner()
                                .HasForeignKey("TrafficLightId");
                        });

                    b.Navigation("CurrentTiming")
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.ValueObjects.PredictionResult", b =>
                {
                    b.HasOne("SmartTrafficLight_Domain.Entities.Intersection", "Intersection")
                        .WithMany()
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartTrafficLight_Domain.ValueObjects.TimingConfig", "SuggestedTiming", b1 =>
                        {
                            b1.Property<Guid>("PredictionResultId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("GreenDuration")
                                .HasColumnType("int")
                                .HasColumnName("SuggestedGreen");

                            b1.Property<int>("RedDuration")
                                .HasColumnType("int")
                                .HasColumnName("SuggestedRed");

                            b1.Property<int>("YellowDuration")
                                .HasColumnType("int")
                                .HasColumnName("SuggestedYellow");

                            b1.HasKey("PredictionResultId");

                            b1.ToTable("PredictionResults");

                            b1.WithOwner()
                                .HasForeignKey("PredictionResultId");
                        });

                    b.Navigation("Intersection");

                    b.Navigation("SuggestedTiming")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartTrafficLight_Domain.Entities.Intersection", b =>
                {
                    b.Navigation("TrafficDatas");

                    b.Navigation("TrafficLights");
                });
#pragma warning restore 612, 618
        }
    }
}
